[oauth]
client_id = "135447600769-22vd8jk726t5f8gp58robppv0v8eeme7.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://google-ads-utility-135447600769.europe-west9.run.app"
